const fakeRestaurants = [
	{
		name: 'Гурман',
		address: 'м. Речной вокзал',
		rating: 4.5,
		reviews: 76,
		img: 'https://resizer.otstatic.com/v2/photos/wide-medium/3/51998483.webp',
		averageBill: 1000,
	},
	{
		name: 'Итальянское наслаждение',
		address: 'м. Преображенская площадь',
		rating: 4.8,
		reviews: 92,
		img: 'https://resizer.otstatic.com/v2/photos/wide-medium/3/27748532.webp',
		averageBill: 2000,
	},
	{
		name: 'Уютный уголок',
		address: 'м. Курская',
		rating: 4.3,
		reviews: 64,
		img: 'https://resizer.otstatic.com/v2/photos/wide-medium/1/25153597.webp',
		averageBill: 3000,
	},
	{
		name: 'Азиатская кухня',
		address: 'м. Чистые пруды',
		rating: 4.7,
		reviews: 81,
		img: 'https://resizer.otstatic.com/v2/photos/wide-medium/3/51998483.webp',
		averageBill: 1000,
	},
	{
		name: 'Пикник',
		address: 'м. Таганская',
		rating: 4.4,
		reviews: 55,
		img: 'https://resizer.otstatic.com/v2/photos/wide-medium/3/27748532.webp',
		averageBill: 2000,
	},
	{
		name: 'Французская кухня',
		address: 'м. Баррикадная',
		rating: 4.6,
		reviews: 69,
		img: 'https://resizer.otstatic.com/v2/photos/wide-medium/1/25153597.webp',
		averageBill: 3000,
	},
	{
		name: 'Семейное кафе',
		address: 'м. Площадь революции',
		rating: 4.2,
		reviews: 47,
		img: 'https://resizer.otstatic.com/v2/photos/wide-medium/3/51998483.webp',
		averageBill: 1000,
	},
	{
		name: 'Стейкхаус',
		address: 'м. Новокузнецкая',
		rating: 4.9,
		reviews: 105,
		img: 'https://resizer.otstatic.com/v2/photos/wide-medium/3/27748532.webp',
		averageBill: 2000,
	},
	{
		name: 'Морепродукты',
		address: 'м. Парк культуры',
		rating: 4.7,
		reviews: 88,
		img: 'https://resizer.otstatic.com/v2/photos/wide-medium/1/25153597.webp',
		averageBill: 3000,
	},
	{
		name: 'Веганская кухня',
		address: 'м. Маяковская',
		rating: 4.0,
		reviews: 39,
		img: 'https://resizer.otstatic.com/v2/photos/wide-medium/3/51998483.webp',
		averageBill: 1000,
	},
];

export default fakeRestaurants;
